services:
  desafio.presentation.api:
    image: dimastorres/desafiopresentationapi
    container_name: desafio-api
    build:
      context: .
      dockerfile: Desafio.Presentation.API/Dockerfile
    ports:
      - 32780:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: ["desafio-db"]
    networks:
      desafio-networks:

  desafio-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=Senha@123"
    ports:
      - 1200:1433
    volumes:
      - "desafio-db-mssql-server:/var/opt/mssql"
    networks:
       desafio-networks:
         aliases:
            - "sqlserver"     

volumes:
  desafio-db-mssql-server:
    
networks:
  desafio-networks:
    driver: bridge